# Generated by Django 5.0.6 on 2024-05-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAsistencia', '0002_estudiante_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='password',
        ),
    ]
